import { z } from 'zod'; import { DoctorProfile } from '../models/doctor-profile.model.js'; import { PatientCase } from '../models/case.model.js'; import { Consultation } from '../models/consultation.model.js'; import { PatientProfile } from '../models/patient-profile.model.js'; import { Vital } from '../models/vital.model.js'; import { Document } from '../models/document.model.js'; import { AYUSHProfile } from '../models/ayush-profile.model.js'; import { HttpError } from '../utils/http-error.js';
export const statusInput=z.object({status:z.enum(['pending_review','reviewed','consultation_in_progress','completed'])}); const med=z.object({name:z.string().min(1).max(200),dosage:z.string().max(100).optional(),frequency:z.string().max(100).optional(),duration:z.string().max(100).optional(),instructions:z.string().max(500).optional()}); const vitals=z.object({temperature:z.number().min(25).max(45).optional(),bloodPressure:z.string().max(30).optional(),heartRate:z.number().int().min(20).max(300).optional(),spo2:z.number().min(0).max(100).optional(),bloodGlucose:z.number().min(0).max(1000).optional()}).optional(); export const consultationInput=z.object({doctorId:z.string().min(1),reason:z.string().min(1).max(500),observations:z.string().max(3000).optional(),clinicalNotes:z.string().max(5000).optional(),assessment:z.string().max(3000).optional(),plan:z.string().max(3000).optional(),medications:z.array(med).default([]),vitals});
async function doctor(doctorId:string){const item=await DoctorProfile.findOne({doctorId});if(!item)throw new HttpError(404,'Doctor not found');return item;} async function caseById(caseId:string){const item=await PatientCase.findOne({caseId});if(!item)throw new HttpError(404,'Case not found');return item;}
export async function listCases(doctorId:string,status?:string){await doctor(doctorId);return PatientCase.find(status?({status} as any):{}).populate('patient','patientId age sex').sort({submittedAt:-1});}
export async function caseDetail(doctorId:string,caseId:string){await doctor(doctorId);const item=await caseById(caseId);const [patient,vitalList,docs,ayush,history]=await Promise.all([PatientProfile.findById(item.patient),Vital.find({patient:item.patient}).sort({recordedAt:-1}).limit(5),Document.find({patient:item.patient}).sort({uploadedAt:-1}).limit(5),AYUSHProfile.findOne({patient:item.patient}),PatientCase.find({patient:item.patient}).sort({submittedAt:-1}).select('caseId intake.complaint status submittedAt')]);return {case:item,patient,vitals:vitalList,documents:docs,ayush,history};}
export async function updateStatus(caseId:string,input:unknown){const item=await caseById(caseId);item.status=statusInput.parse(input).status;await item.save();return item;}
async function doctorVitals(patient:any,caseRef:any,input:any){if(!input)return [];const anyValue=Object.values(input).some(Boolean);if(!anyValue)return [];return [await Vital.create({patient,case:caseRef,source:'doctor',...input})];}
export async function createConsultation(caseId:string,input:unknown){const item=await caseById(caseId);if(await Consultation.findOne({case:item._id}))throw new HttpError(409,'Consultation already exists for this case');const data=consultationInput.parse(input),doc=await doctor(data.doctorId),vitalRefs=await doctorVitals(item.patient,item._id,data.vitals);const created=await Consultation.create({...data,doctor:doc._id,case:item._id,vitals:vitalRefs.map(v=>v._id),startedAt:new Date()});item.status='consultation_in_progress';await item.save();return created;}
export async function getConsultation(caseId:string){const item=await caseById(caseId);const consultation=await Consultation.findOne({case:item._id}).populate('vitals');if(!consultation)throw new HttpError(404,'Consultation not found');return consultation;}
export async function updateConsultation(caseId:string,input:unknown){const item=await caseById(caseId);const existing=await Consultation.findOne({case:item._id});if(!existing)throw new HttpError(404,'Consultation not found');const data=consultationInput.partial().parse(input);if(data.vitals){const refs=await doctorVitals(item.patient,item._id,data.vitals);data.vitals=undefined;existing.vitals.push(...refs.map(v=>v._id));}Object.assign(existing,data);await existing.save();return existing;}
export async function completeConsultation(caseId:string,input:unknown){const item=await caseById(caseId);const existing=await Consultation.findOne({case:item._id});if(!existing)throw new HttpError(404,'Consultation not found');if(existing.status==='completed')throw new HttpError(409,'Consultation is already completed');const data=consultationInput.partial().parse(input);Object.assign(existing,data,{status:'completed',completedAt:new Date()});await existing.save();item.status='completed';await item.save();return {consultation:existing,case:item};}
