import { z } from 'zod'; import { PatientProfile } from '../models/patient-profile.model.js'; import { PatientCase } from '../models/case.model.js'; import { Counter } from '../models/counter.model.js'; import { Vital } from '../models/vital.model.js'; import { AYUSHProfile } from '../models/ayush-profile.model.js'; import { HttpError } from '../utils/http-error.js';
export const caseInput=z.object({complaint:z.string().min(1).max(300),duration:z.string().min(1).max(100),severity:z.string().min(1).max(100),symptoms:z.array(z.string().max(150)).default([]),medications:z.array(z.string().max(150)).default([]),allergies:z.string().max(300).default(''),healthHistory:z.string().max(1000).default(''),redFlags:z.array(z.string().max(200)).default([]),verificationNeeded:z.array(z.string().max(200)).default([])});
export const vitalInput=z.object({temperature:z.number().min(25).max(45).optional(),bloodPressure:z.string().max(30).optional(),heartRate:z.number().int().min(20).max(300).optional(),spo2:z.number().min(0).max(100).optional(),bloodGlucose:z.number().min(0).max(1000).optional()}).refine(v=>Object.keys(v).length>0,'Provide at least one vital');
export const ayushInput=z.object({system:z.string().min(1).max(100),prakriti:z.string().max(200).optional(),vikriti:z.string().max(200).optional(),ahaar:z.string().max(500).optional(),lifestyle:z.string().max(500).optional(),sleep:z.string().max(300).optional(),remedies:z.string().max(500).optional()});
async function patient(patientId:string){const item=await PatientProfile.findOne({patientId});if(!item)throw new HttpError(404,'Patient not found');return item;}
export async function getProfile(patientId:string){return patient(patientId)}
export async function createCase(patientId:string,input:unknown){const profile=await patient(patientId), intake=caseInput.parse(input);const counter=await Counter.findByIdAndUpdate('caseId',{$inc:{sequence:1}},{upsert:true,new:true});const caseId=`SS-S${String(counter.sequence).padStart(3,'0')}`;return PatientCase.create({patient:profile._id,caseId,intake,status:'pending_review'});}
export async function listCases(patientId:string){const profile=await patient(patientId);return PatientCase.find({patient:profile._id}).sort({submittedAt:-1}).select('caseId intake.complaint status submittedAt');}
export async function getCase(patientId:string,caseId:string){const profile=await patient(patientId);const item=await PatientCase.findOne({patient:profile._id,caseId});if(!item)throw new HttpError(404,'Case not found for this patient');return item;}
export async function updateCase(patientId:string,caseId:string,input:unknown){const parsed=caseInput.partial().parse(input);const item=await getCase(patientId,caseId);Object.assign(item.intake,parsed);await item.save();return item;}
export async function addVital(patientId:string,input:unknown){const profile=await patient(patientId);return Vital.create({patient:profile._id,...vitalInput.parse(input),source:'patient'});}
export async function listVitals(patientId:string){const profile=await patient(patientId);return Vital.find({patient:profile._id,source:'patient'}).sort({recordedAt:-1});}
export async function getAyush(patientId:string){const profile=await patient(patientId);return AYUSHProfile.findOne({patient:profile._id});}
export async function putAyush(patientId:string,input:unknown){const profile=await patient(patientId);return AYUSHProfile.findOneAndUpdate({patient:profile._id},{...ayushInput.parse(input),patient:profile._id},{new:true,upsert:true,runValidators:true});}
export async function history(patientId:string){const profile=await patient(patientId);return PatientCase.find({patient:profile._id}).sort({submittedAt:-1}).select('caseId intake.complaint status submittedAt');}
