import { useState } from 'react';
import { Bell, ChevronRight, Clock3, FileText, HeartPulse, History, Leaf, Plus, ScanLine, ShieldCheck, Stethoscope, Upload, UserRound, Wind } from 'lucide-react';
import { Brand } from './components/Brand';
import { Icon } from './components/Icon';
import { BottomNav, SideNav, type View } from './components/Navigation';
import { doctorCases, questions } from './services/mockService';

const stats=[['Today’s patients','12',UserRound,'sage'],['Pending cases','5',Clock3,'sand'],['Reports to review','8',FileText,'blue'],['Follow-ups','3',History,'lilac']] as const;
const vitals=[['Blood pressure','120/80 mmHg'],['Temperature','36.6°C'],['Heart rate','72 bpm'],['SpO₂','98%']];
function Header({doctor=false}:{doctor?:boolean}){return <header className="topbar"><Brand/><div className="header-actions"><button className="icon-button" aria-label="Notifications"><Bell size={19}/><i/></button><button className="avatar" aria-label="Open profile">{doctor?'AH':'AN'}</button></div></header>}
function PatientDashboard({setView}:{setView:(view:View)=>void}){return <><Header/><main><section className="welcome"><div><h1>Hello, Aisha <span>👋</span></h1><p>Thursday, 11 September 2026</p></div><span className="status">♡ Feeling well today?</span></section><section className="case-hero"><div className="featured"><span>✦ FEATURED</span><div><button aria-label="Message"><Wind size={19}/></button><button aria-label="Voice input"><HeartPulse size={19}/></button></div></div><h2>Patient Case</h2><p>Tell us what you’re experiencing.</p><div className="tags"><span>⌁ Symptoms</span><span>◷ History</span><span>♧ Allergies</span></div><button className="primary wide" onClick={()=>setView('case')}><Plus size={19}/> Start Case</button></section><section className="section-title"><h3>Quick Access</h3><button>See all <ChevronRight size={16}/></button></section><section className="quick-grid"><article className="quick-card history"><span className="large-icon"><History/></span><h3>Health History</h3><p>All your medical records in one place.</p><button onClick={()=>setView('history')}>View History <ChevronRight size={16}/></button></article><article className="quick-card vitals"><span className="large-icon"><Stethoscope/></span><h3>Vitals Mode</h3><p>Track your readings.</p><dl>{vitals.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl></article><article className="mini-card"><Upload/><div><b>Documents</b><span>Upload & verify reports</span></div><ChevronRight/></article><article className="mini-card"><Leaf/><div><b>AYUSH profile</b><span>Complete your wellness intake</span></div><ChevronRight/></article></section></main></>}
function DoctorDashboard(){return <><Header doctor/><main><section className="doctor-greeting"><h1>Good morning, Dr. Amelia Hayes</h1><p>You have 12 patients and 5 pending cases today.</p></section><section className="section-title"><h3>Today’s overview</h3><span>Thu, 11 Sep</span></section><section className="stats">{stats.map(([label,value,icon,tone])=><article className="stat-card" key={label}><span className={'stat-icon '+tone}><Icon icon={icon}/></span><b>{value}</b><p>{label}</p></article>)}</section><section className="cases"><section className="section-title"><h3>Patient cases</h3><span className="ai-ready">✦ 3 AI ready</span></section>{doctorCases.map(person=><article className="patient-card" key={person.id}><div className={'patient-avatar '+person.tone}>{person.initials}</div><div className="patient-main"><div className="case-heading"><div><h3>{person.name}</h3><p>{person.gender} · {person.age} · ID #{person.id.slice(3)}</p></div><time><Clock3 size={14}/>{person.time}</time></div><small>CHIEF COMPLAINT</small><p className="complaint">{person.complaint} — {person.description}</p>{person.ready&&<span className="ai-ready">✦ AI case summary ready</span>}<div className="case-actions"><button>View case</button><button className="primary">Start consultation</button></div></div></article>)}</section></main></>}
function Questionnaire({setView}:{setView:(view:View)=>void}){const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<Record<string,string>>({}); const question=questions[index]; const choose=(answer:string)=>{const next={...answers,[question.id]:answer};setAnswers(next); if(index===questions.length-1)setView('summary'); else setIndex(index+1)}; return <><Header/><main className="flow"><button className="back" onClick={()=>setView('patient')}>← Back to home</button><div className="progress"><span>Step {index+1} of {questions.length}</span><div><i style={{width:`${((index+1)/questions.length)*100}%`}}/></div></div><section className="question-card"><span className="eyebrow">YOUR HEALTH CHECK-IN</span><h1>{question.title}</h1>{question.hint&&<p>{question.hint}</p>}<div className="options">{question.options.map(option=><button key={option} onClick={()=>choose(option)}><span/> {option}<ChevronRight size={19}/></button>)}</div></section><p className="safety-note"><ShieldCheck size={17}/> This helps prepare your case for a clinician. It does not provide a diagnosis.</p></main></>}
function Summary({setView}:{setView:(view:View)=>void}){return <><Header/><main className="flow"><button className="back" onClick={()=>setView('patient')}>← Back to home</button><section className="summary-card"><span className="eyebrow">CASE COMPLETE</span><h1>Your patient summary</h1><p className="summary-disclaimer">✦ AI-assisted summary — clinician verification required.</p><div className="summary-grid"><div><small>MAIN COMPLAINT</small><b>Headache</b></div><div><small>DURATION</small><b>1–3 days</b></div><div><small>SEVERITY</small><b>Moderate</b></div><div><small>ASSOCIATED SYMPTOMS</small><b>Fatigue</b></div></div><div className="missing"><ScanLine size={20}/><div><b>Information to verify</b><p>Allergy information should be confirmed during consultation.</p></div></div><div className="redflag"><b>Red flags</b><span>No warning signs recorded</span></div><button className="primary wide" onClick={()=>setView('patient')}>Return to dashboard</button></section></main></>}
function HistoryPage({setView}:{setView:(view:View)=>void}){return <><Header/><main><button className="back" onClick={()=>setView('patient')}>← Back to home</button><section className="history-header"><div><span className="eyebrow">YOUR RECORDS</span><h1>Health history</h1><p>A clear timeline of your care, documents and readings.</p></div><button className="icon-button"><History/></button></section><div className="filters"><button>All records⌄</button><button>Newest first⌄</button><label>⌕ <input placeholder="Search your history"/></label></div><section className="timeline"><h3>2026</h3>{[['11 Sep','Patient case','Headache check-in','In progress'],['18 Jul','Prescription','Dr. Meera Shah','Verified'],['04 Mar','Vitals update','Blood pressure and SpO₂','Recorded']].map(([date,title,detail,status])=><article key={date}><time>{date}</time><span className="timeline-dot"/><div><b>{title}</b><p>{detail}</p><em>{status}</em></div></article>)}</section></main></>}
export function App(){const [view,setView]=useState<View>('patient'); const [role,setRole]=useState<'patient'|'doctor'>('patient'); const content=view==='doctor'?<DoctorDashboard/>:view==='case'?<Questionnaire setView={setView}/>:view==='summary'?<Summary setView={setView}/>:view==='history'?<HistoryPage setView={setView}/>:<PatientDashboard setView={setView}/>;return <div className="app"><SideNav role={role} view={view} setView={setView}/><div className="page"><div className="mode-switch"><button className={role==='patient'?'selected':''} onClick={()=>{setRole('patient');setView('patient')}}>Patient view</button><button className={role==='doctor'?'selected':''} onClick={()=>{setRole('doctor');setView('doctor')}}>Doctor view</button></div>{content}</div>{role==='patient'&&<BottomNav view={view} setView={setView}/>}</div>}
